# Generated by Django 3.2.14 on 2022-07-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_auto_20220707_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
